### ISSUE TITLE
Style warning compiling RANDOM-INT

### ISSUE THREAD

**Issue by rpgoldman** [Shinmera/random-state#16]
ASDF loading random state on SBCL I see this:

```
 caught STYLE-WARNING:
;   2 calls to RANDOM-STATE:RANDOM-FLOAT were compiled before a compiler-macro was
;   defined for it. A declaration of NOTINLINE at the call sites will eliminate
;   this warning, as will defining the compiler-macro before its first potential
;   use.
; in: DEFUN RANDOM-INT
;     (< RANDOM-STATE::TO RANDOM-STATE::FROM)
```

TBQH I find this warning message deeply, deeply cryptic.  I thought it might be the compiler macros being defined before `random-int`, but that is not it. 

To the extent possible, I will look for more information about this error _not_ embedded in a bunch of my code.

**Comment by rpgoldman** [comment]
In generator.lisp we see `define-generator-fun` for `seed` on line 76.

It looks like this is referenced by the `print-object` method on line 48.

Similarly, the `defun` for `random` in protocol.lisp calls `random-float`, whose compiler-macro is defined on line 87.

**Comment by Shinmera** [comment]
Fixed in latest
