### ISSUE TITLE
Error loading library from quicklisp on LispWorks

### ISSUE THREAD

**Issue by ELind77** [Shinmera/random-state#2]
When loading for the first time from quicklisp (compiling) I got a complaint that something was being called with the argument :HOMEPAGE.  I'm guessing that this relates to quicklisp and not to LispWorks, but you never know. 

I told it to ignore the argument and it seemed to compile ok.  Let me know if you want me to test anything.

**Comment by Shinmera** [comment]
The homepage argument is an ASDF3 feature. All of my systems and plenty others in Quicklisp use it and other features ASDF3 brings with it. You should really consider upgrading your ASDF version.

**Comment by ELind77** [comment]
I didn't realize.  And yes, it's probably my lispworks image.  I'll see if I can do something about it.  Sorry for opening unnecessary issue.  Thanks for your prompt response though, and the library is great! 

Eric

**Comment by Shinmera** [comment]
I'm glad to help. If there's anything else, don't hesitate to drop me another line/mail/issue.
