### ISSUE TITLE
random-state does not compile on Clozure CL

### ISSUE THREAD

**Issue by rpgoldman** [Shinmera/random-state#22]
When I try, I get an error: 

    Can't reseed RANDOM-STATE objects on Clozure Common Lisp.

Looking for a patch.

**Comment by rpgoldman** [comment]
See #23 

Note that this isn't the optimal solution to this problem. I think a better one would be to replace the existing `random-state` generator implementation with one that *wraps* a `cl:random-state` instead of just using the `cl:random-state`.

Then, instead of having to operate on the implementations' random-states in this ugly way, involving use of lots of unexported functions, we could just *replace* the contained random-state object with a new one, while keeping the identity of the generator.

But for now I think it would be best just to merge this to solve the critical problem, and get a better solution when someone has more time.

**Comment by Shinmera** [comment]
I've converted it to a warning instead.
