### ISSUE TITLE
Does `benchmark` have to be upstream of `generator`?

### ISSUE THREAD

**Issue by rpgoldman** [Shinmera/random-state#42]
CCL's compiler doesn't like it that `benchmark` is defined (in `toolkit.lisp`) before `generator.lisp` is loaded.  It says this:

```
Compiler warnings for "home:lisp;shop;jenkins;ext;random-state;toolkit.lisp.newest" :
;   In BENCHMARK: INLINE declaration for unknown function ENSURE-GENERATOR
;   In BENCHMARK: Unknown type (FUNCTION (GENERATOR) T), declaration ignored
```

I would like to pull the two benchmark functions out and put them in "histogram.lisp", since they are not called so only need to be defined by the time "random-state" is completely loaded.

If you are ok with that, I'll send another PR.  But please let me know if there is some reason I should _not_ do this.

**Comment by rpgoldman** [comment]
See #43

**Comment by Shinmera** [comment]
nah, seems fine.
