### ISSUE TITLE
Why subtract epsilon?

### ISSUE THREAD

**Issue by slburson** [Shinmera/random-state#44]
My program did `(random 0.0)` and got back a small negative number, and I was curious as to why.  It's evidently because `random` on a single-float (for example) subtracts `single-float-epsilon` from the supplied `max` argument.  I'm trying to understand why you did this.  Is it because it's possible for `random-float` to return a value equal to `to`?  In that case, shouldn't you be doing `(- max (* max single-float-epsilon))`?

**Comment by slburson** [comment]
BTW, related to a comment in `random`, SBCL's `short-float` is the same as `single-float` on every platform; I can see this from a look at `src/code/early-float.lisp` in the SBCL tree.  Looks like there's a build-time option to use x86 long floats for `long-float`, but it's disabled by default.

**Comment by Shinmera** [comment]
Yeah, `random-float` is inclusive, while `cl:random` is exclusive, see the documentation.

**Comment by slburson** [comment]
Sorry, I should have been clearer.  I understand that zero is not intended to be a valid argument; it just happened that my program had a bug that caused it to try `(random 0.0)`, and when the answer came back negative, I was startled and wondered why.

Anyway, I should have explained the point of multiplying the epsilon value by the max before subtracting.  If someone does `(random 4.0)`, then they might get back exactly 4.0; the subtraction won't have any effect, because by definition, there aren't enough bits in a single-float to represent `(- 4.0 single-float-epsilon)`.  What's much worse, if they do `(random 5e-8)`, they'll get back a negative number, because `5-e8` is less than `single-float-epsilon`.  If you multiply first, as I suggested, these problems go away.

... No, wait!  I've now studied your code a little more closely, and concluded that contrary to the documentation, `random-float` can't actually return a value equal to `to`.  There are three cases.  In the case where `from` is a constant (as it is, of course, when called from `random`), the compiler macro handles it and calls `(random-bytes 24)`, which returns a value in `[0, 2^24)`, then scales that by `2^-24`.  That operation cannot return 1.0, as you can see by trying the largest possible value:

```
> (scale-float 16777215.0 -24)
0.99999994
```

If the compiler macro doesn't kick in, then we wind up in `random-unit`, which in turn has two cases, but AFAICT neither of them can return `to` exactly.  The integer case is as above, and if the generator returns floats directly, `next-byte` is documented not to return 1.0.  (I didn't check the implementations to verify that it can't.)

Sooooo, given all that, seems like you shouldn't be subtracting the epsilon value in `random` at all.  Or, maybe you should be subtracting it in `random` and adding it back in `random-float`, to make the latter match its documentation, although in my opinion a reasonable alternative would be just to change the documentation; there's no risk of breaking user code because there's only a `2^-24` chance of that value being returned on any given call anyway.

**Comment by slburson** [comment]
You're welcome!
